### ISSUE TITLE
Page title uses the first heading instead of _config.yml values

### ISSUE THREAD

**Issue by bitcoinx2** [pages-themes/cayman#105]
I'm having this problem with my Github page: https://github.com/titcoin/titcoin.github.io

In _config.yml, I have configured the title and description as:

```
title: Titcoin
description: The adult cryptocurrency
```

However, the page title comes out as:

`<title>Welcome to Titcoin! | Titcoin</title>`

What I would expect is:

`<title>Titcoin | The adult cryptocurrency</title>`

On https://pages-themes.github.io/cayman/ it seems to work as expected and the first heading is not used. So is this a bug, or am I misunderstanding something? How can I make the page title look as described above?

**Comment by deirdresm** [comment]
The default is set up here on line 26 & 27: https://github.com/pages-themes/cayman/blob/7269e0563fc074edd9c7ff1588424e7caf1d2ed5/_layouts/default.html

So that should help you set up your titles and descriptions accordingly.

**Comment by bitcoinx2** [comment]
Thanks! I explicitly set the "title" and "description" front matter tags in the index.md file (in addition to _config.yml) and now it works as expected. :)
