### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by benthecoder** [pages-themes/cayman#110]
Any idea how I can add dark mode to this theme with a stylesheet? Thank you.

**Comment by KTibow** [comment]
I implemented something that works for me. See https://github.com/KTibow/fridge/blob/main/assets/css/style.scss.

**Comment by KTibow** [comment]
You should probably adapt it so it looks good for your website instead of copy/pasting.

**Comment by benthecoder** [comment]
> You should probably adapt it so it looks good for your website instead of copy/pasting.

Alright thanks for the tip! I was a bit confused because I'm new to the hsl and hsla color format.

I'm actually having trouble changing the section heading color of red, could you point out which line will allow me to change that color?

**Comment by KTibow** [comment]
It's this bit: https://github.com/KTibow/fridge/blob/main/assets/css/style.scss#L48-L55

**Comment by benthecoder** [comment]
> It's this bit: https://github.com/KTibow/fridge/blob/main/assets/css/style.scss#L48-L55

Ah that makes sense. Thanks so much!

**Comment by lewismiddleton** [comment]
For anyone else that's looking into this, I made a dark mode fork of the Cayman theme. Here's a link to the repo https://github.com/lewismiddleton/cayman-dark
