### ISSUE TITLE
Posts Not Apearing On index.md

### ISSUE THREAD

**Issue by cjbohlman** [pages-themes/cayman#112]
Hello, I just started using this theme and I was wondering why my post is not appearing on the home page of my GitHub pages website. I can still access the post through url/YYYY/MM/DD/TITLE, but I was wondering how I can get that post (and all future posts in the _post directory) to automatically show. Is that possible with cayman?

Thank you.

**Comment by parkr** [comment]
Hi! This theme does not natively support posts. If you would like to add them to your site, you're welcome to follow the tutorial here: https://jekyllrb.com/docs/step-by-step/08-blogging/#list-posts
