### ISSUE TITLE
Color variables not working

### ISSUE THREAD

**Issue by djedi** [pages-themes/cayman#12]
I'm trying to override the color variables as described in the readme but it is not working. Anyone else having issues?

Here is my `assets/css/style.scss`

```sass
$header-bg-color: #6E4D9B;
$header-bg-color-secondary: #E82887;
$section-headings-color: #6E4D9B;

@import "{{ site.theme }}";
```

**Comment by benbalter** [comment]
Those changes have not yet been released. See https://github.com/pages-themes/cayman/compare/v0.0.4...master.

**Comment by djedi** [comment]
Is there a way I can specify using v0.0.4?

**Comment by willclarktech** [comment]
Really looking forward to this feature - any idea when it'll be released?

**Comment by menehune23** [comment]
I'm using the latest as of this week and it looks like it's 0.0.4 (`bundle show cayman`), and I'm still not seeing this work. Am I missing something?

**Comment by robsonbittencourt** [comment]
Using version 0.0.4 and don't work here too.

**Comment by robsonbittencourt** [comment]
@benbalter Sorry for the mistake, I had understood that it was in version 0.4.0 that was available.

I saw that you have now made version 0.1.0. Should it be working now, or do you still have a publishing process? I tested here and did not succeed.

I created the `assets/css/style.scss` file with the following content:

```sass
$header-bg-color: #1e6bb8;
$header-bg-color-secondary: #7EA7D3;

$body-link-color: #7EA7D3;
$blockquote-text-color: #819198;

$code-text-color: #494D4E;

@import "{{ site.theme }}";
```

**Comment by benbalter** [comment]
It should work on version 0.1.0 (currently live on GitHub Pages). If it does not work, I'd ask the others on this thread to help troubleshoot, as this is a bit beyond my area of expertise.

**Comment by robsonbittencourt** [comment]
Of course, I can help with some other test if necessary. But I do not know much about it either.

What I did for now was to copy the entire _sass directory of this project to my project, replacing the color variables.

Follow the repository link if it is useful: https://github.com/robsonbittencourt/jenkins-dry-in-pipelines

**Comment by seanperera** [comment]
I managed to change the colors by following the instructions on https://github.com/pages-themes/cayman#stylesheet. See below for an example of the style.scss file. if you don't add the --- lines then the colours won't change. 

```
---
---

// Breakpoints
$large-breakpoint: 64em !default;
$medium-breakpoint: 42em !default;

// Headers
$header-heading-color: #fff !default;
$header-bg-color: #f39c12;
$header-bg-color-secondary: #e67e22;

// Text
$section-headings-color: #D35400;
$body-text-color: #606c71 !default;
$body-link-color: #1e6bb8 !default;
$blockquote-text-color: #819198 !default;

// Code
$code-bg-color: #f3f6fa !default;
$code-text-color: #567482 !default;

// Borders
$border-color: #dce6f0 !default;
$table-border-color: #e9ebec !default;
$hr-border-color: #eff0f1 !default;

@import "{{ site.theme }}";
```
