### ISSUE TITLE
Add support for Google Analytics 4

### ISSUE THREAD

**Issue by lolgear** [pages-themes/cayman#122]
Hi!
It would be nice to have support for Google Analytics 4 ( gtag ).

```yaml
/// _config.yml
google-analytics: G-xxxxxxxx
```

**Comment by get-itips** [comment]
Also interested on this...

**Comment by parkr** [comment]
Hi! You can now customize this with v0.2.0. The Google Analytics code is now an include so you can overwrite it in your site: https://github.com/pages-themes/cayman#customizing-google-analytics-code

**Comment by lolgear** [comment]
Does it work?

I guess you have to add gtag.


<script async src="https://www.googletagmanager.com/gtag/js?id={{ site.site.google_analytics }}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'site.google_analytics');
</script>
