### ISSUE TITLE
[Feature Request] Can we have user defined buttons in header?

### ISSUE THREAD

**Issue by skygragon** [pages-themes/cayman#13]
in the same line with "View Github" button

**Comment by jmgirard** [comment]
It might be nice to have the ability to add these through the config file. However, it is relatively easy to edit the default.html file to add and customize such buttons.

1. Create new file in your master or gh-pages branch called `_layouts/default.html`
2. Edit the default.html file to add a link to the "page-header" section and give it class="btn"
3. You can use Jekyll variables prepopulated by GitHub in these buttons

For example, add the following to add buttons to the "releases" and "wiki" pages:
```
<section class="page-header">
      <h1 class="project-name">{{ site.title | default: site.github.repository_name }}</h1>
      <h2 class="project-tagline">{{ site.description | default: site.github.project_tagline }}</h2>
      {% if site.github.is_project_page %}
        <a href="{{ site.github.repository_url }}" class="btn">View Source Code</a>
      {% endif %}
      {% if site.show_downloads %}
        <a href="{{ site.github.zip_url }}" class="btn">Download .zip</a>
        <a href="{{ site.github.tar_url }}" class="btn">Download .tar.gz</a>
      {% endif %}
      <a href="{{ site.github.releases_url }}" class="btn">Download Program</a>
      <a href="{{ site.github.wiki_url }}" class="btn">View Documentation</a>
</section>
```
