### ISSUE TITLE
SCSS build error for GitHub Pages

### ISSUE THREAD

**Issue by DaveSkender** [pages-themes/cayman#131]
I can't tell if this is Cayman template specific, but am getting errors in [my GitHub Pages build](https://github.com/DaveSkender/Stock.Indicators/runs/3147778780) about this template.

```bash
GitHub Pages failed to build your site.
Your SCSS file assets/css/style.scss has an error on line 3: File to import not found or unreadable: cayman. 
Load path: /tmp/jekyll-remote-theme-20210723-7-m9rhj/_sass.
```

When I try to build locally:

```bash
Configuration file: C:/Users/../_config.yml
jekyll 3.9.0 | Error: The jekyll-theme-cayman theme could not be found.
```

**Comment by blackstarzes** [comment]
I'm getting the [same issue](https://github.com/veelourenco/veelourenco.github.io/runs/3148205278). It looks like this repo is failing at [cd47cc1](https://github.com/pages-themes/cayman/commit/cd47cc1f2ab43bd75321d06e56414e5a806ebe4a).

**Comment by DaveSkender** [comment]
I think this has more to do with a recent [github-pages](https://github.com/github/pages-gem/pull/772/files) merge that bumps it to version 216.  This may occur when `bundle update` happens and it is updated automatically.

If I force it back to version 215 in the GemFile it seems to work okay.

```yaml
gem 'github-pages', "~>215"
```

**Comment by blackstarzes** [comment]
Hmmm... no that still didn't work for me - I get the [same error in build](https://github.com/veelourenco/veelourenco.github.io/runs/3148413029). I am just going to disable Jekyll and serve a static site until this is resolved.

**Comment by joolfe** [comment]
Same error in my repo, any clues about what happen?

**Comment by blackstarzes** [comment]
So pinning github-pages to 215 worked locally, but not when running on GitHub. I ended up moving the theme's scss files to my repo, which led to some yak-shaving to see how much of the theme I actually used, and subsequent removal of the theme dependency. Sorry if that doesn't help you 😅.

**Comment by AnonyPla** [comment]
See https://github.com/pages-themes/cayman/issues/130#issuecomment-886056882

**Comment by joolfe** [comment]
For me the solution proposed in #130 works, just replace

´@import "{{ site.theme }}";´

to

´@import 'jekyll-theme-cayman';´

**Comment by Jmuccigr** [comment]
This works for me too, Yes, this works for me too with the minimal theme, but it's more a work-around than a fix, no? The theme should be import-able from the config file without hardcoding it into the scss.

**Comment by DaveSkender** [comment]
I think this is related to an update to the GitHub Pages theme manager (see my [comment above](https://github.com/pages-themes/cayman/issues/131#issuecomment-885973017)).

If you look at their merged PR from yesterday, they move from Gem based to remote based theme management.  I’m going to also take a look at implementing with [jekyll-remote-theme](https://github.com/benbalter/jekyll-remote-theme) for my Pages site to see if that’s a working alternative.

**Comment by DaveSkender** [comment]
To get this to work locally (and with publish), here's my workflow:

```bash
# remove old artifacts
bundle exec jekyll clean
```

```bash
# leave this in your _config.yml
theme: jekyll-theme-cayman
```

```bash
# as mentioned in recommendation above
# add explicit include in your custom assets/css/style.scss file
# replace @import "{{ site.theme }}"; with
@import "jekyll-theme-cayman";
```

```bash
# add theme as an explicit jekyll plugin to GemFile
# do not just cmd line `gem install jekyll-theme-cayman`
group :jekyll_plugins do
  gem 'github-pages'
  gem 'jekyll-theme-cayman'
end
```

```bash
# load site locally, to test
bundle install
bundle update #optional
bundle exec jekyll serve
```

**Comment by Jmuccigr** [comment]
> My observation on the bug is that `bundle update` will set `github-pages` to version 216 and `jekyll-theme-cayman` is removed from the GemFile.lock dependencies list -- it's basically not included as a sub-dependency Gem anymore.

Well, my Gemfile.lock includes both cayman and minimal, even after the `bundle update github-pages` which moved me to 216. I have to admit that I don't quite understand what's going on here when jekyll says it can't find the theme file when it's there.

In any case, [that update](https://github.com/github/pages-gem/pull/772) seems like it broke things for a lot of people. It also seems to have some code to try to convert themes to remote themes which I guess didn't work (or isn't supposed to do what I think). Not a great experience in any case.

**Comment by AnonyPla** [comment]
I tried reverting to 215 just to see but it didn't help ... anyway ... my fix https://github.com/pages-themes/cayman/issues/130#issuecomment-886056882 and this one https://github.com/pages-themes/cayman/issues/131#issuecomment-886092689 work so we have a workaround

**Comment by parkr** [comment]
> File to import not found or unreadable: cayman

This should now be fixed on GitHub Pages and in the GitHub-pages gem locally.

> jekyll 3.9.0 | Error: The jekyll-theme-cayman theme could not be found.
 
I'm really sorry about this, but this slipped past our testing. I have added an upgrading note to v216 and v217 of the `github-pages` gem, e.g. https://github.com/github/pages-gem/releases/tag/v217.
