### ISSUE TITLE
Tables not rendering correctly?

### ISSUE THREAD

**Issue by yammadev** [pages-themes/cayman#15]
Hi there, I'm using a table like this in my `readme`:

```
Flag | Code |Region
:---: | :---: | :---
![AD](png/EU.png)   | EU    | European Union
![AE](png/WW.png)   | WW    | World
![CNA](png/CNA.png) | CNA   | North America
![CSA](png/CSA.png) | CSA   | South America
```

In the [repository](https://github.com/yammadev/flag-icons) it seems to render correctly, however, in the [page](https://yammadev.github.io/flag-icons/) it does not. Am I doing something wrong? :confused:

**Comment by benbalter** [comment]
Please see https://help.github.com/articles/organizing-information-with-tables/ for the proper syntax for formatting tables.

**Comment by yammadev** [comment]
I corrected it according to the guide, however, the result is the same. Any idea?

**Comment by benbalter** [comment]
@yammadev if you contact [GitHub support](https://github.com/support), they should be able to look into your site more closelt.
