### ISSUE TITLE
Feature request: "on this page" mini TOC

### ISSUE THREAD

**Issue by noamtamim** [pages-themes/cayman#16]
As seen on [Leap Day](https://pages-themes.github.io/leap-day/). 

I prefer this theme visually, but the on-this-page TOC is a nice touch.

**Comment by brandoncurtis** [comment]
These GitHub Pages are built with Jekyll using the `kramdown` Markdown converter.

You can add a Table of Contents to a page like this:

```markdown
* Will be replaced with the ToC
{:toc}
```

+ https://kramdown.gettalong.org/converter/html.html#toc

**Comment by noamtamim** [comment]
@brandoncurtis Any idea how I can apply the configuration options mentioned in the page you linked, such as `toc_levels` to a page hosted on GHP?

**Comment by noamtamim** [comment]
Never mind, found the question myself. For future me (or others):

https://help.github.com/articles/configuring-jekyll/
