### ISSUE TITLE
[Feature request] replace hard-coded tag "theme-color" with variable

### ISSUE THREAD

**Issue by ChrisADR** [pages-themes/cayman#18]
Hi :)

It would be nice if the hard-coded meta tag "theme-color" is changed with a variable, I'd love to do it myself and send my PR, but I'm learning Ruby and I don't know if what I'm asking is even possible, but it would be nice since I've been looking for that value like 10 times on each CSS file.

Thanks

**Comment by benbalter** [comment]
@ChrisADR if you replace the hard-coded theme color in https://github.com/pages-themes/cayman/blob/93ce3c3895f733a27064dd48555a27d61065eb5a/_layouts/default.html#L8 with `{{ site.theme_color | default: "#15787" }}`, I believe it should achieve your desired functionality.

**Comment by ChrisADR** [comment]
#19 then this may help a bit to make it easier to find :) 

thanks for the info, hope it helps 
Christopher Díaz Riveros
