### ISSUE TITLE
"View On GitHub" button not work for organization pages

### ISSUE THREAD

**Issue by cavivie** [pages-themes/cayman#197]
Cayman uses `is_project_page` of [github-metadata](https://github.com/jekyll/github-metadata/blob/main/lib/jekyll-github-metadata/repository.rb#L152-L183) to check the project is github pages or not, but for this case, the checked result is the project is user page (that is `is_user_page` is true):
https://github.com/rust-open-games/rust-open-games.github.io

I must set `is_project_page` to true to enable "View On Github" button on pages view.

I don't know, is this an incorrect behavior of `github-metadata`, or is it `cayman`, worse case, that I understand it wrong?

**Comment by michaelconan** [comment]
I experienced the same behavior:
- links showed in local testing of site
- initial deployment (without `is_project_page`) on GitHub pages did not show link
- addition of this configuration allowed links to be shown

**Comment by cavivie** [comment]
Many thanks, I think it was resolved now.
