### ISSUE TITLE
Table shows correctly in the markdown but NOT in cayman theme.

### ISSUE THREAD

**Issue by raul1991** [pages-themes/cayman#20]
Here is how it looks in the markdown preview in github

![image](https://user-images.githubusercontent.com/1281636/29443139-b3a909b6-83f3-11e7-9d0c-ff291b435c7d.png)

When I apply cayman theme using github

![image](https://user-images.githubusercontent.com/1281636/29443186-f79d7b84-83f3-11e7-8de7-14d0dad03930.png)

**Comment by benbalter** [comment]
I can't speak to the specifics of your site. If you [contact GitHub support](https://github.com/contact) they should be able to help you get things straightened out.
