### ISSUE TITLE
Configure "View on GitHub" to link to organisation page

### ISSUE THREAD

**Issue by leif81** [pages-themes/cayman#25]
In my GitHub organization (https://github.com/open-dis), I've got a repository dedicated to hosting the content for our website (https://github.com/open-dis/open-dis.org) and we're using this Jekyll Cayman theme. The problem is the "View on GitHub" link that is generated directs people to the repository for the website content, which is not really useful. Instead if the button linked to the top level GitHub organisation page (e.g. https://github.com/open-dis) it'd be more useful so that the user could browse the repos the organisation offers.

I get that the current behaviour works if someone were publishing their web site under the `gh-pages` branch. But for standalone website repositories I think the behaviour of the button could be better as mentioned above.

**Comment by martinbarge** [comment]
If I understand correctly what you are aiming to do, you can customise the template and CSS files of your GitHub web pages, by adding a default.html file and scss file. Once you've done this, you can then edit the default.html file template "page-header" and "site-footer" sections replacing the URLs with the one to want.

Instructions on customising teh CSS and HTML are here: [https://help.github.com/articles/customizing-css-and-html-in-your-jekyll-theme/]((https://help.github.com/articles/customizing-css-and-html-in-your-jekyll-theme/) )

**Comment by martinbarge** [comment]
Just a quick additional note. In the default.html file, edit this in the "page-header" section:
`<a href="{{ site.github.repository_url }}" class="btn">View on GitHub</a>`
To:
`<a href="{{ site.github.url }}" class="btn">View on GitHub</a>`

Do the same to the entry in the footer.

**Comment by benbalter** [comment]
You do not need to modify the template. You can set the following in your site's config to override the GitHub-supplied default:

```yml
github:
  repository_url: http://example.com
```

**Comment by leif81** [comment]
Thank you both. I went with @benbalter's suggestion, it seemed easiest for me.

**Comment by Kief5555** [comment]
> You do not need to modify the template. You can set the following in your site's config to override the GitHub-supplied default:
> 
> ```yaml
> github:
>   repository_url: http://example.com
> ```

Where would I put that if I am using github pages? (html)

**Comment by retrohacking** [comment]
> 

in _config.yml

**Comment by retro4hack** [comment]
> > You do not need to modify the template. You can set the following in your site's config to override the GitHub-supplied default:
> > ```yaml
> > github:
> >   repository_url: http://example.com
> > ```
> 
> Where would I put that if I am using github pages? (html)

in _config.yml

**Comment by rmiddle** [comment]
> ```yaml
> github:
>   repository_url: http://example.com
> ```

Worked great.
