### ISSUE TITLE
style.css not found when hosting on Github Pages

### ISSUE THREAD

**Issue by AlexPoint** [pages-themes/cayman#26]
Hi,

I'm new to Jekyll & Github Pages so I'm probably missing something obvious here but I cannot find what.
style.css is loaded in default.html via 
`<link rel="stylesheet" href="{{ '/assets/css/style.css?v=' | append: site.github.build_revision | relative_url }}">`
So on Github Pages hosting, the url for this stylesheet is https://alexpoint.github.io/assets/css/style.css?v=33125130a4821c5cff85754a283fd242618965dd
and it's actual location is 
https://alexpoint.github.io/remedes/assets/css/style.css?v=33125130a4821c5cff85754a283fd242618965dd
Any idea what I'm missing here to have the name of the repository included in the URL?

Thanks

**Comment by benbalter** [comment]
We can't speak to the specifics of your site just by looking at two URLs. If you [contact GitHub support](https://github.com/contact) they should be able to help you get things straightened out.
