### ISSUE TITLE
How can you run the styling for GitHub pages off local styling?

### ISSUE THREAD

**Issue by ItsPugle** [pages-themes/cayman#28]
I want to have complete control of the styling, but I want to base it off Cayman, so how can I import the styling code from here into my own repository, then set the repository to load that style instead?

**Comment by benbalter** [comment]
@ItsPugle see https://github.com/pages-themes/cayman#stylesheet.

**Comment by ItsPugle** [comment]
Thanks for that Ben, but I'd like to have absolute full control over the site. Is there a guide anywhere that will show me how to bring the styling across to my repository, and the changes that I may need to make to the config?

**Comment by ItsPugle** [comment]
Nevermind! I did some more looking around and was able to bring the styling across!
