### ISSUE TITLE
Disabling the "View on GitHub" button?

### ISSUE THREAD

**Issue by ItsPugle** [pages-themes/cayman#29]
I want to disable the "View on GitHub" button from my site, as the source code is currently in a private repository. Is there a setting for _config.yml that the it will do it?

**Comment by benbalter** [comment]
@ItsPugle Ideally there'd be a dedicated setting, but I believe you can add the following to your site's config to trick it into not displaying the badge:

```yml
github:
  is_project_page: false
```

**Comment by guidozuc** [comment]
@benbalter trick works.

**Comment by ItsPugle** [comment]
^

**Comment by noratanxz** [comment]
I copy and paste the exact thing into my _config.yml but it isn't doing the trick for some reason - it still shows up :(

**Comment by xiaodaigh** [comment]
> your site's config

is this the _config.yml file? I added that bit but it doesn't work.

**Comment by dentex** [comment]
Same. It doesn't seem to work anymore.

**Comment by dconlrn** [comment]
Any quick fix for this yet or do we need to read a bunch of books as usual ?

**Comment by korsbakken** [comment]
It works for me. But I had to wait for several minutes after pushing the change to _config.yml before it worked. Seems like the old version either sticks around on the github.io server for quite some time, or there is some caching in the browser. Maybe shut down the browser and restart if it doesn't work after 10-15 minutes?
