### ISSUE TITLE
Custom CSS not beign processed

### ISSUE THREAD

**Issue by vorov2** [pages-themes/cayman#3]
I have created a custom CSS as described in documentation. File 'style.css' is placed at /assets/css/style.css:

https://github.com/vorov2/slot/edit/master/assets/css/style.css

However, styles from CSS are ignored.

**Comment by benbalter** [comment]
@vorov2 there is a typo in the documentation. Can you please try renaming the file to `style.scss` (note the S in the extension).

@parkr should the theme logic overwrite `style.css` if it exists in the site (but `style.scss` exists for the theme)?

**Comment by vorov2** [comment]
@benbalter I am getting the following error now:

> Your SCSS file `assets/css/style.scss` has an error on line 1: File to import not found or unreadable: . Load path: /hoosegow/.bundle/ruby/2.3.0/gems/jekyll-theme-cayman-0.0.3/_sass. For more information, see https://help.github.com/articles/page-build-failed-invalid-sass-or-scss.

**Comment by benbalter** [comment]
@vorov2 Thanks for the additional information. You're doing everything right, but I believe you've found a bug. We've identified the root cause, and will reply here when we have it fixed.

**Comment by benbalter** [comment]
Also, @vorov2 as a temporary workaround, you can replace that first line with `@import "jekyll-theme-cayman";` and your site should build as expected.

**Comment by vorov2** [comment]
Thanks, that worked.

**Comment by benbalter** [comment]
This has been fixed and `{{ site.theme }}` should work properly once again.
