### ISSUE TITLE
Description meta tag is included twice in the head tag

### ISSUE THREAD

**Issue by braek** [pages-themes/cayman#30]
In the default layout the description meta tag is included twice.

First through the SEO plugin:

`{% seo %}`

Second hard coded in the head tag itself:

`<meta name="description" content="{{ page.description | default: site.description | default: site.github.project_tagline }}"/>`

This is duplicate information and causes the W3C HTML validator to generate a warning about it.

**Comment by braek** [comment]
@benbalter I'm using this theme for my own personal website (hosted through GitHub Pages).

When will the change be available there? :-)

**Comment by benbalter** [comment]
Looking at https://github.com/pages-themes/cayman/blob/master/_layouts/default.html, I don't believe this to be the case anymore. Please comment if that is not true.
