### ISSUE TITLE
Add default favicon <link>-tag to <head>

### ISSUE THREAD

**Issue by Wikxen** [pages-themes/cayman#32]
Since most sites use favicons including them in <head> if available would be a good idea

**Comment by thepaintedbeat1** [comment]
Where do I add it?

Sincerely,

From


Marguerite Apotre
Founder of The Painted Beat
Calgary Branch Director of God Loves Profit

Phone: 403-656-9299
Web: www.thepaintedbeat.com

**Comment by Wikxen** [comment]
I made a PR #33 that describes one way to do it. (i.e. how I did it)

**Comment by brolaugh** [comment]
I guess there would have to be a check for whether `favicon.ico` exists and based on that  render the HTML PR #33 suggests be added.
