### ISSUE TITLE
Can I customize syntax highlighting theme for code blocks?

### ISSUE THREAD

**Issue by thawsitt** [pages-themes/cayman#36]
I am using gh-pages to generate a web page for my repo (mostly markdown files). Is there an easy way I can edit the syntax highlighting theme using _config.yml file?

**Comment by benbalter** [comment]
Yes. You'll want to customize https://github.com/pages-themes/cayman/blob/master/_sass/rouge-github.scss, placing the modified file in your `_sass` folder (or simply overriding individual CSS selectors followiing [these instructions](https://github.com/pages-themes/cayman#stylesheet).
