### ISSUE TITLE
Syntax highlighting for C++ code doesn't seem to be work

### ISSUE THREAD

**Issue by faheel** [pages-themes/cayman#37]
I recently published a repo of mine, [BigInt](https://github.com/faheel/BigInt), as a [GitHub pages site](https://faheel.github.io/BigInt/) using the Cayman theme, but the code blocks marked as 'C++', like:

    ```C++
    // some C++ code here...
    ```
do not get syntax highlighted. On inspecting the generated HTML, I see that the class `language-C++` is added on the `<code>` elements, but there's no syntax highlighting on them.

**Comment by benbalter** [comment]
Try `cpp` instead of `c++`?

**Comment by faheel** [comment]
@benbalter Thanks! Both lowercase variants, `cpp` and `c++`, work.

**Comment by faheel** [comment]
Still, this behaviour is inconsistent with the rendering of Markdown files on GitHub. Should I report it to [jekyll/jekyll](https://github.com/jekyll/jekyll), or is the syntax highlighting for GitHub Pages handled by some other utility?

**Comment by shawnajean** [comment]
👋 [Syntax highlighting for Pages is handled by Rouge](https://help.github.com/articles/using-syntax-highlighting-on-github-pages/), Jekyll's default syntax highlighter. You can see the list of supported languages & their abbreviations here:

https://github.com/jneen/rouge/wiki/List-of-supported-languages-and-lexers

**Comment by faheel** [comment]
@shawnajean Thanks!
