### ISSUE TITLE
google-analytics

### ISSUE THREAD

**Issue by rastamanjohn** [pages-themes/cayman#39]
I'm kinda new to github, I'm trying to make a webpage at rastamanjohn.github.io. I saw in the README.md i can add a analytics tracking ID in the _config.yml, but I imagine that I shouldn't push the file with my ID. So how do I have it on my page without making it available to everyone?

**Comment by benbalter** [comment]
Google Analytics tracking IDs are public, not secret. The worst a malicious user could do is spoof traffic to your site, which you can counter, if you're concerned by specifying the domain.

**Comment by rastamanjohn** [comment]
Ok, didn't know that, thank you!
