### ISSUE TITLE
No Download Button

### ISSUE THREAD

**Issue by CodingWithAdin** [pages-themes/cayman#42]
Hi there!
So i have a problem where on my gitHub page there is no download buttons. 
I tried changing the theme, and same thing happens. So this is not a specific theme issue, this is issue of all themes

**Comment by benbalter** [comment]
We can't speak to the specifics of your particular site. If you [contact GitHub support](https://github.com/contact) (or [post to the GitHub Community forum](https://github.community/)) they should be able to help you get things straightened out. 😸
