### ISSUE TITLE
GH pages preview is using master-branch for the preview (not actual latest release)

### ISSUE THREAD

**Issue by escapedcat** [pages-themes/cayman#55]
It looks like if I am setting up GH pages with one of their default themes I do not get the latest HTML/CSS. What am I missing?

How come HTML structure looks [like this](https://escapedcat.github.io/github-pages-test/)?:

```html
<body>
    <section class="page-header">
    </section>

    <section class="main-content">
    </section>
</body>
```

And not [like this](https://pages-themes.github.io/cayman/)?:

```html
<body cz-shortcut-listen="true">
    <a id="skip-to-content" href="#content">Skip to the content.</a>

    <header class="page-header" role="banner">
    </header>

    <main id="content" class="main-content" role="main">
    </main>
</body>
```

According to [the latest `default` template of **cayman**](https://github.com/pages-themes/cayman/blob/master/_layouts/default.html#L25) it should use `header`, `main` and have a *scip to content* link.

I created this test repo to describe my issue: https://github.com/escapedcat/github-pages-test

This is not a specific problem of the cayman theme. I have the same problem with other default themes. I just didn't know where exactly to raise this issue/question.  
Please let me know if I should move this to somewhere else.

**Comment by escapedcat** [comment]
@benbalter this is related to the unaligned github-pages theme preview and the actual used theme during the creation of the static files (which is using `0.1.1` in most/all themes).  
  
![cayman-preview](https://user-images.githubusercontent.com/1016218/49375245-0fb12e80-f704-11e8-9c17-76ea92557d60.png)  

This is so confusing.  
I think most themes should either
- create a new release to be aligned with the github-pages preview
- github-pages preview should use latest release of a theme instead of *master*

I am not sure where else reporting this would make more sense. Maybe here?: https://github.com/github/pages-gem

**Comment by escapedcat** [comment]
I wrote to the GH supoort. The replied that they will pass it on to the team. Let's see if that helps. Would be great.

**Comment by escapedcat** [comment]
@dubreuia this issue still exists right? Looks like issues in this repo aren't really maintained and then get closed by the bot. Pity.

@slgraff said he'll pass it on to the team early December 2018. Not sure what the status is. I'll ask.

**Comment by dubreuia** [comment]
@escapedcat Yes it still exists. I feel like this isn't really maintained anymore, couldn't find the source code for the hosted template. I finally rewrote the template so I don't really need it anymore.

**Comment by escapedcat** [comment]
@dubreuia the sourcecode for the hosted template in the GH preview is the master-branch of this repo. The source for the installed version you get is [the latest release here from April 2018](https://github.com/pages-themes/cayman/releases).
