### ISSUE TITLE
Can't change default.html or stylesheet.

### ISSUE THREAD

**Issue by haakonms** [pages-themes/cayman#57]
Hey, I cloned this repo locally and opened it in webstorm. I wan't to change default.html, config.yml and the stylesheet, but everything just automatically resets to the original content (except config which just stays the same. Do I have to do things step-by-step in the readme to make things work?

<img width="1440" alt="skjermbilde 2018-12-10 kl 22 31 27" src="https://user-images.githubusercontent.com/43436737/49798134-dbf88900-fd41-11e8-9b4e-cbc778ee6fee.png">

**Comment by WeileiZeng** [comment]
i have this issue too. Any solution?

I modify the default.html, but nothing changes.
