### ISSUE TITLE
List not rendering inside <details> tag

### ISSUE THREAD

**Issue by giacomodeliberali** [pages-themes/cayman#60]
Hi guys, I have an issue rendering the table of content of the readme which is wrapped inside a collapasble panel (`<details></details>`). The readme contains:

```html
<details>
  <summary>Table of contents</summary>
- [Introduction](#introduction)
- [Cloud Computing Reference Model](#cloud-computing-reference-model)
- [Data centers](#data-centers)
...
</details>
```
Which in the readme is displayed as 
<details>
  <summary>Table of contents</summary>

-  [Introduction](#introduction)
-  [Cloud Computing Reference Model](#cloud-computing-reference-model)
-  [Data centers](#data-centers)
- ...
</details>

<br>
But in the theme is shown as:

![screenshot 2019-01-14 at 13 55 12](https://user-images.githubusercontent.com/4717227/51113934-10a9a580-1804-11e9-949d-6ce39350b854.png)

Other lists outside details tag are properly converted to `<ol>` and `<li>` elements. Any suggestions on how to fix this? Thanks!

**Comment by benbalter** [comment]
@giacomodeliberali I haven't tested with GitHub Pages, but on GitHub.com, you'll need to add new lines around the markdown inside HTML to get it to render. If that doesn't work, please contact GitHub Support and they can look into your specific case.

**Comment by giacomodeliberali** [comment]
Ok, the issue happens when serving the readme from GitHub pages whit this theme. Btw I'll give it a try, thank you
