### ISSUE TITLE
How can I add an image to the header page?

### ISSUE THREAD

**Issue by JuliaTorrejon** [pages-themes/cayman#65]
I would like to know how to add a custom header image.

![header image](https://user-images.githubusercontent.com/29682284/54497043-f2d4eb80-48ed-11e9-860c-a4d469683e23.png)

Thanks for your help.

**Comment by LeapofAzzam** [comment]
It's easy. To add the image to the header page, open _layouts/default.html
In the ```<header>``` section, you must replace the following code:
```html
      <h1 class="project-name">{{ page.title | default: site.title | default: site.github.repository_name }}</h1>
      <h2 class="project-tagline">{{ page.description | default: site.description | default: site.github.project_tagline }}</h2>
```
To this:
```html
      <img src="(your image URL address)" alt="{{ page.title | default: site.title | default: site.github.repository_name }}" class="project-name" />
      <h2 class="project-tagline">{{ page.description | default: site.description | default: site.github.project_tagline }}</h2>
```
In the code replace again "(your image URL address)" to your image URL address. If you add this in ```_config.yml```:
```yaml
logo: /assets/images/logo.png
```
Or if you add this in your Markdown/HTML file at a top of a file content:
```
---
image: /assets/images/(your image file)
---
```
You can replace the code to this:
```html
      <img src="{{ page.image | default: site.logo }}" alt="{{ page.title | default: site.title | default: site.github.repository_name }}" class="project-name" />
      <h2 class="project-tagline">{{ page.description | default: site.description | default: site.github.project_tagline }}</h2>
```
Thanks for your help. 
— [Leap of Azzam](https://www.github.com/LeapofAzzam)

**Comment by LeapofAzzam** [comment]
> I would like to know how to add a custom header image.
> 
> ![header image](https://user-images.githubusercontent.com/29682284/54497043-f2d4eb80-48ed-11e9-860c-a4d469683e23.png)
> 
> Thanks for your help.

Yes, it's easy. To add the image to the header page, open _layouts/default.html
In the ```<header>``` section, you must replace the following code:
```html
      <h1 class="project-name">{{ page.title | default: site.title | default: site.github.repository_name }}</h1>
      <h2 class="project-tagline">{{ page.description | default: site.description | default: site.github.project_tagline }}</h2>
```
To this:
```html
      <img src="(your image URL address)" alt="{{ page.title | default: site.title | default: site.github.repository_name }}" class="project-name" />
      <h2 class="project-tagline">{{ page.description | default: site.description | default: site.github.project_tagline }}</h2>
```
In the code replace again "(your image URL address)" to your image URL address. If you add this in ```_config.yml```:
```yaml
logo: /assets/images/logo.png
```
Or if you add this in your Markdown/HTML file at a top of a file content:
```
---
image: /assets/images/(your image file)
---
```
You can replace the code to this:
```html
      <img src="{{ page.image | default: site.logo }}" alt="{{ page.title | default: site.title | default: site.github.repository_name }}" class="project-name" />
      <h2 class="project-tagline">{{ page.description | default: site.description | default: site.github.project_tagline }}</h2>
```
— [Leap of Azzam](https://www.github.com/LeapofAzzam)

**Comment by VascoRibeiroPereira** [comment]
Hello, Hope if anyone can help with this one:
I wanted to add an image as the header background. Is it possible? The way here described includes an image on the header only I think (at least that is my test results)

thank you for your help

**Comment by hohwille** [comment]
Is this theme and repo dead or what?
Such an obvious question is not responed in years?
Added logo to `_config.yml`(see e.g. https://github.com/pages-themes/minimal/blob/master/_config.yml#L2)  - no effect on site.
Added the following header to `README.md` (see e.g. https://github.com/ifremer-bioinformatics/ifremer-bioinformatics.github.io/blob/master/index.md?plain=1#L2):
```
---
image: /logo.svg
---
```
Now pipeline "pages build and deployment" succeeded but website is gone (404).

Seriously?

**Comment by clearhythm** [comment]
It's easy enough if you customize your Jekyll theme. You can see an example here of Cayman with a logo at the top:
http://airstreamjs.com/

All I did was create a folder in the root of my project called
_layouts

and then copied Cayman's default.html into that folder. You can find that here
https://github.com/pages-themes/cayman/blob/master/_layouts/default.html

In the header block, you can update how the header functions. My header section looks like this

    <header class="page-header" role="banner">
      <img class="logo" src="assets/img/logo_blimp.png" alt="airstream.js logo" width="475" height="235" />
      <h1 class="project-name">{{ page.title | default: site.title | default: site.github.repository_name }}</h1>
      <h2 class="project-tagline">{{ page.description | default: site.description | default: site.github.project_tagline }}</h2>
      {% if site.github.is_project_page %}
        <a href="{{ site.github.repository_url }}" class="btn">View on GitHub</a>
      {% endif %}
      {% if site.show_downloads %}
        <a href="{{ site.github.zip_url }}" class="btn">Download .zip</a>
        <a href="{{ site.github.tar_url }}" class="btn">Download .tar.gz</a>
      {% endif %}
    </header>

And as you can see, includes my image block at the top, which is what causes the logo to appear.

You can style pages too by adding a /assets/css/style.scss file.
You can see this reference for inspiration:
https://jekyllrb.com/docs/themes/

Good luck!
Erik

**Comment by nilsanilsson** [comment]
This worked, thanks a lot!

I am trying to use the Cayman theme, and I would like to replace the entire green-ish banner at the top with a picture of my choice. Any idea how that can be achieved?

Thanks!
Albin


> It's easy enough if you customize your Jekyll theme. You can see an example here of Cayman with a logo at the top: http://airstreamjs.com/
> 
> All I did was create a folder in the root of my project called _layouts
> 
> and then copied Cayman's default.html into that folder. You can find that here https://github.com/pages-themes/cayman/blob/master/_layouts/default.html
> 
> In the header block, you can update how the header functions. My header section looks like this
> 
> ```
> <header class="page-header" role="banner">
>   <img class="logo" src="assets/img/logo_blimp.png" alt="airstream.js logo" width="475" height="235" />
>   <h1 class="project-name">{{ page.title | default: site.title | default: site.github.repository_name }}</h1>
>   <h2 class="project-tagline">{{ page.description | default: site.description | default: site.github.project_tagline }}</h2>
>   {% if site.github.is_project_page %}
>     <a href="{{ site.github.repository_url }}" class="btn">View on GitHub</a>
>   {% endif %}
>   {% if site.show_downloads %}
>     <a href="{{ site.github.zip_url }}" class="btn">Download .zip</a>
>     <a href="{{ site.github.tar_url }}" class="btn">Download .tar.gz</a>
>   {% endif %}
> </header>
> ```
> 
> And as you can see, includes my image block at the top, which is what causes the logo to appear.
> 
> You can style pages too by adding a /assets/css/style.scss file. You can see this reference for inspiration: https://jekyllrb.com/docs/themes/
> 
> Good luck! Erik

**Comment by andreazignoli** [comment]
You can modify a couple of lines in the `_sass/jekyll-them-cayman.scss file`.
In my case, what I did was: 
```
  background-image: url("./../../my_cool_image.jpg");
  background-size: 100% auto;
```
The second line is used to resize your image so it's not cropped, etc. If you don't want to use a local image I suppose you can use a link to an online figure.
