### ISSUE TITLE
Google analytics switching to analytics.js

### ISSUE THREAD

**Issue by slowtick** [pages-themes/cayman#7]
Google Analytics suggests [upgrading to analytics.js](https://developers.google.com/analytics/devguides/collection/upgrade/) for all users. Had this changed for [my page layout](https://github.com/slowtick/slowtick.github.io/blob/34977ea25b795bb5c57e95b432859924b8e9324e/_layouts/default.html#L171) and tested ok.

Would you like a pull request for this change?

**Comment by benbalter** [comment]
> Would you like a pull request for this change?

Yes please!

**Comment by slowtick** [comment]
Thanks for the merge 👍
