### ISSUE TITLE
How can I add an sidebar to the site page?

### ISSUE THREAD

**Issue by LeapofAzzam** [pages-themes/cayman#71]
I created a website using Cayman theme but I can't add the sidebar to the site page. How can I add an sidebar to the site page?
![IMG_20190423_115320](https://user-images.githubusercontent.com/48548847/56555219-6f7a7a00-65be-11e9-95b3-cd659f7deee6.JPG)

**Comment by dubaut** [comment]
I'd love to know that, too!

**Comment by daenifae** [comment]
I am also struggling with this! Overriding the default layout does not seem to allow the addition of navigation. Admittedly I don't have a lot of experience in doing this, but have been able to manipulate other themes to get the result I want.
