### ISSUE TITLE
Issues adding Google-Analytics to the page

### ISSUE THREAD

**Issue by MarkL4YG** [pages-themes/cayman#73]
Hey there,  
I am quite confused by having to ask this here, but: I don't seem able to enable the Google Analytics tag of the Cayman theme.  😕 
According to the read me, the only thing to do is setting ``google_analytics`` in the ``_config.yml`` and even the if-clause in the layout file looks like this should be working.  
However, after adding the tracking ID, the corresponding GH-page still does not render the analytics tag 🤔   
Here is the link to the repository: https://github.com/jeakfrw/jeakfrw.github.io 
  
Thank you in advance

**Comment by sdgandhi** [comment]
You don't see the googletagmanager script in the <head>?

Did you check that adblocker isn't blocking the script download?

**Comment by MarkL4YG** [comment]
I don't use a classical adblocker and turned off content blocking too.  
The script tag was just not rendering upon page generation.  
  
At the moment I have worked around that issue by adding the tag manually to the template.

**Comment by sdgandhi** [comment]
In the linked repository, I don't seem to see the google_analytics key in _config.yaml. 

Does it render in development at least (bundle exec jekyll serve)?

**Comment by MarkL4YG** [comment]
That's because of [this commit](https://github.com/jeakfrw/jeakfrw.github.io/commit/2420b8de6a0ebacf65364d49d12dde0b85c9c3da) in which I temporarily removed it from the configuration file and statically added GA to the template html file.

It does show up in my local development environment, yes.  
I have also tried to enable it again right now and it appears to show up as intentioned, although I don't know whether or not GitHub is deploying instantly for GH pages.

**Comment by sdgandhi** [comment]
Hmm weird. It usually takes ~1 minute for the build. Glad it's working now!

**Comment by MarkL4YG** [comment]
Yeah, I cannot really explain this either. But hey, it works now. Thanks for your time anyways. :)
