### ISSUE TITLE
How do you disable the View on GitHub button?

### ISSUE THREAD

**Issue by BOLTZZ** [pages-themes/cayman#76]
How do you disable the view on github button for your github page. Putting github:
  is_project_page: false in _config.yml doesn't work. Please help!!

**Comment by BOLTZZ** [comment]
This is my code in _config.yml:
github:
  is_project_page: false
theme: jekyll-theme-cayman
The button is still there.

**Comment by BOLTZZ** [comment]
Nvm, i just had to update some minor things.

**Comment by miakurt** [comment]
How do I remove View on GitHub button? And how do I remove in footer miakurt is maintained by miakurt.
This page was generated by GitHub Pages.
And how do I publish my page? Thank you.

**Comment by KraigWastlund** [comment]
> Nvm, i just had to update some minor things.

What did you have to update @BOLTZZ ??

**Comment by BOLTZZ** [comment]
@KraigWastlund This was a year and a half ago, I don't remember what I did. Try searching the online forums or github forums?

**Comment by BOLTZZ** [comment]
Also, I'm not sure if what I did works anymore, as I was viewed my Github Pages site and it still has the mark.
