### ISSUE TITLE
Tables are not rendering in page 

### ISSUE THREAD

**Issue by yammadev** [pages-themes/cayman#82]
Hello there, I'm facing a problem with tables rendering, this is my code:

```md
| Flag                | Code | Region         |
|:--------------------|:-----|:---------------|
| ![AD](png/EU.png)   | EU   | European Union |
| ![AE](png/WW.png)   | WW   | World          |
| ![CNA](png/CNA.png) | CNA  | North America  |
| ![CSA](png/CSA.png) | CSA  | South America  |
| ![CEU](png/CEU.png) | CEU  | Europe         |
| ![CAF](png/CAF.png) | CAF  | Africa         |
| ![CAS](png/CAS.png) | CAS  | Asia           |
| ![COC](png/COC.png) | COC  | Oceania        |
```

and it looks like: 

![image](https://user-images.githubusercontent.com/12621550/76727546-54f34700-6722-11ea-80ca-de567503a28f.png)

However in `readme.md` is rendering correctly:

![image](https://user-images.githubusercontent.com/12621550/76727791-02665a80-6723-11ea-8764-10613d9e2582.png)

This is my [live site](https://yammadev.github.io/flag-icons/) to check it out.

**Comment by ms-studio** [comment]
Indeed, the Markdown parsing in README files is different from the parsing in Github Pages.

To make the table work, just add an empty line between the header and the table.

This has probably something to do with the Markdown parser defined in Jekyll... see https://help.github.com/en/github/working-with-github-pages/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll

> GitHub Pages supports two Markdown processors: kramdown and GitHub's own extended CommonMark processor, which is used to render GitHub Flavored Markdown (GFM) throughout GitHub.

You could change the setting in `_config.yml` from "kramdown" to "GFM" and see if this helps.

**Comment by yammadev** [comment]
> This is my [live site](https://yammadev.github.io/flag-icons/) to check it out.

@ms-studio Thank you very much! That solved my issue, now it's working as expected.

**Comment by lmjaedentai** [comment]
markdown:  kramdown
