### ISSUE TITLE
How do I change the title of index page

### ISSUE THREAD

**Issue by rahulrajpl** [pages-themes/cayman#84]
When I use this theme via settings>GitHub pages themes for a repo, default title is taken as the repo name and description as repo description.

I have created an index.md file with front matter including 'title' and 'description'. But it doesn't seem to work. Is there a workaround or is it normal behavior?

**Comment by ms-studio** [comment]
If you want to change the default title and description, you have to change those values in the following file: `_config.yml`

**Comment by rahulrajpl** [comment]
Thanks, that worked.
