### ISSUE TITLE
some pages shift when viewed on desktop

### ISSUE THREAD

**Issue by Lnk2past** [pages-themes/cayman#87]
Hi there! I am a newbie when it comes to any amount of web development, so I apologize if this is not a direct issue with the cayman theme (which is amazing, by the way!).

I found that some pages on my website are shifting to the left when viewed on desktop. This does not happen on mobile (at least not on my phone, neither portrait nor landscape). I have not modified the theme, just mostly adding content and throwing some things from other tutorials in.

For reference, my site is https://www.nesware.io and the source code is https://github.com/NESWare/NESWare.github.io. The Home page, About page, and all blog posts share the same shift and the Blog and Projects pages share the same shift. I have zero clue as to why.

If anyone can point me in the right direction to debug this it would be much appreciated.

**Comment by KTibow** [comment]
This is on purpose. Things would look weird if they were centered on mobile. Here's the problem-causer:
https://github.com/pages-themes/cayman/blob/d4cdac15d273c45cb6d9a0b1d2772a21008ea063/_sass/jekyll-theme-cayman.scss#L169-L184
@Lnk2past I'm sending in a PR that should fix that.

**Comment by KTibow** [comment]
Basically follow the instructions for changing the css, and style however you want.
