### ISSUE TITLE
How do i set up a favicon?

### ISSUE THREAD

**Issue by officialnico** [pages-themes/cayman#93]
ive been trying for a while and i cant seem to figure it out heres my repo 
https://github.com/officialnico/eatsweb
[](https://github.com/officialnico/eatsweb)

**Comment by officialnico** [comment]
I figured it out. So just go to https://github.com/pages-themes/cayman and download the _layouts folder and then move that into your root folder. edit default.html, just on top of </head> write this down
 `<link rel="shortcut icon" type="image/png" href="favicon.png">` 
and have the favicon png you want to use in your root folder.
then go into _config.yml and put under plugins
`plugins:
  - jekyll-seo-tag`

**Comment by 030** [comment]
@officialnico Could you add this functionality to the template as well to prevent that the default.html has to be copied?

**Comment by Banty300** [comment]
✅ This is a test PR to complete GitHub Task for Authena Points!
